resolver: lts-8.23

# I had problems with libffi and pkg-config until I did this.
packages:
  - .
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: master
    extra-dep: true
flags:
  idris:
    FFI: true
    GMP: true

extra-deps:
  - libffi-0.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
